### PR TITLE
Port to WebKit2-4.0-API

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Not tested.  Let me know if you had test results.

**Comment by chimosky** [comment]
No errors in webkit port, I'll open an issue(s) for other encountered problems.

**Comment by quozl** [comment]
Thanks.  No need to open issues if you have a fix.  Open pull request if you have a fix.

**Comment by chimosky** [comment]
> No need to open issues if you have a fix. Open pull request if you have a fix.

Thanks, I opened the issue because at the moment i can't work on it, just in case someone else wants to.

**Pull request merged**
